example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# melakukan routing
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import *

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist_html, name='show_mywatchlist_html'),
    path('html/', show_mywatchlist_html, name='show_mywatchlist_html'),
    path('xml/', show_mywatchlist_xml, name='show_mywatchlist_xml'),
    path('json/', show_mywatchlist_json, name='show_mywatchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path("todolist/", include("todolist.urls")),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = "todolist"

urlpatterns = [
    path("", show_todolist, name="show_todolist"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("create-task/", create_task, name="create_task"),
    path("json/", show_todolist_json, name="show_todolist_json"),
    path("add/", add_task, name="add")
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class WatchlistMovie(models.Model):
    watched = models.CharField(max_length=3)
    title = models.CharField(max_length=50)
    rating = models.CharField(max_length=1)
    release_date = models.CharField(max_length=20)
    review = models.TextField()

todolist/models.py
from django.contrib.auth.models import User
from django.db import models

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=50)
    description = models.TextField()

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ["user"]

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
# import untuk mengambil data dari database
from katalog.models import CatalogItem

# membuat fungsi menampilkan katalog
def show_katalog(request):
    # menambahkan context untuk ditampilkan
    data_item_katalog = CatalogItem.objects.all()
    context = {
        'list_item': data_item_katalog,
        'nama': 'Calista Vimalametta Heryadi',
        'npm': '2106630473'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from mywatchlist.models import WatchlistMovie

def show_mywatchlist_html(request):
    watchlist = WatchlistMovie.objects.all()
    context = {"watchlist": watchlist}
    return render(request, "mywatchlist.html", context)

def show_mywatchlist_xml(request):
    watchlist = WatchlistMovie.objects.all()
    return HttpResponse(serializers.serialize("xml", watchlist), content_type="application/xml")

def show_mywatchlist_json(request):
    watchlist = WatchlistMovie.objects.all()
    return HttpResponse(serializers.serialize("json", watchlist), content_type="application/json")

todolist/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from todolist.forms import TaskForm
from todolist.models import Task

@login_required(login_url="/todolist/login/")
def show_todolist(request):
    context = {
        "user": request.user,
        "user_id": request.user.id,
        "tasks": Task.objects.all()
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Akun telah berhasil dibuat!")
            return redirect("todolist:login")
    context = {"form": form}
    return render(request, "register.html", context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("todolist:show_todolist")
        else:
            messages.info(request, "Username atau Password salah!")
    return render(request, "login.html")

def logout_user(request):
    logout(request)
    return redirect("todolist:login")

@login_required(login_url="/todolist/login/")
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            messages.success(request, "Task telah berhasil ditambahkan!")
            return redirect("todolist:show_todolist")
    return render(request, "create_task.html")

def show_todolist_json(request):
    tasks = list(Task.objects.all().values())
    return JsonResponse(tasks, safe=False)

def add_task(request):
    form = TaskForm(request.POST)
    form.instance.user = request.user
    if form.is_valid():
        form.save()
        return JsonResponse({"title": form.instance.title, "date": form.instance.date, "description": form.instance.description})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 2 PBP - Katalog</h1>

  {% comment %} map context dengan sintaks Django {% endcomment %}
  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% for item in list_item %}
      <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP - My Watchlist</h1>

  <p>NOTE: these ratings and reviews are of my own opinion, not from the general reception.</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% for movie in watchlist %}
      <tr>
        <th>{{movie.watched}}</th>
        <th>{{movie.title}}</th>
        <th>{{movie.rating}}</th>
        <th>{{movie.release_date}}</th>
        <th>{{movie.review}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
  <title>Tambah Task Baru</title>
{% endblock meta %}

{% block content %}
  <div class="bg-dark text-white text-center py-3">
    <h1>Tambah Task Baru</h1>
  </div>

  <div class = "container text-center py-3">
    {% if messages %}
      {% for message in messages %}
        <span class="text-danger">{{ message }}</span><br><br>
      {% endfor %}
    {% endif %}

    <form method="POST" action="">
      {% csrf_token %}
      <table class="table table-hover table-borderless align-middle">
        <tr>
          <th>Judul: </th>
          <td><input type="text" name="title" placeholder="Judul" class="form-control" required></td>
        </tr>
        <tr>
          <th>Deskripsi: </th>
          <td><input type="text" name="description" placeholder="Deskripsi" class="form-control" required></td>
        </tr>
      </table>
      <input class="btn btn-dark" type="submit" value="Tambah Task">
    </form>
  </div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
  <title>Login</title>
{% endblock meta %}

{% block content %}
  <div class="bg-dark text-white text-center py-3">
    <h1>Login</h1>
  </div>

  <div class = "container text-center py-3">
    <form method="POST" action="">
      {% csrf_token %}
      <table class="table table-hover table-borderless align-middle">
        <tr>
          <th>Username: </th>
          <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
        </tr>
        <tr>
          <th>Password: </th>
          <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
        </tr>
      </table>
      <input class="btn btn-dark" type="submit" value="Login">
    </form>

    {% if messages %}
      {% for message in messages %}
        <br><span class="text-danger">{{ message }}</span>
      {% endfor %}
    {% endif %}

    <hr>
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
  </div>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
  <title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
  <div class="bg-dark text-white text-center py-3">
    <h1>Registrasi Akun</h1>
  </div>

  <div class = "container text-center py-3">
    <form method="POST" >  
      {% csrf_token %}  
      <table class="table table-hover table-borderless align-middle">  
        {{ form.as_table }}  
      </table>
      <input class="btn btn-dark" type="submit" name="submit" value="Daftar"/>    
    </form>
  </div>  
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
  <title>To-Do List</title>

  <style>
    .card{
      transition: all 0.2s ease;
    }
    .card:hover {
      opacity: 0.8;
      transform: scale(1.1);
    }
  </style>

  <script>
    function appendCard(title, date, description) {
      $("#card-grid").append(`
        <div class="col-sm-6 col-md-4 p-3">
          <div class="card h-100 text-white bg-dark">
            <div class="card-body">
              <h5 class="card-title">${title}</h5>
              <h6 class="card-subtitle text-muted">Dibuat pada ${date}</h6>
              <br>
              <p class="card-text">${description}</p>
            </div>
          </div>
        </div>
      `)
    }
    
    $(document).ready(function() {
      $.get("{% url 'todolist:show_todolist_json' %}", function(tasks) {
        for (const task of tasks) {
          if (task["user_id"] == "{{ user_id }}") {
            appendCard(task["title"], task["date"], task["description"])
          }
        }
      }, "json")

      $("form").submit(function(event) {
        event.preventDefault()
        var form = {
          title: $("#title").val(),
          description: $("#description").val(),
          csrfmiddlewaretoken: "{{ csrf_token }}",
        }
        $.post("{% url 'todolist:add' %}", form, function(task) {
          appendCard(task["title"], task["date"], task["description"])
          $("#modal").modal("hide")
        }, "json")
      })
    })
  </script>
{% endblock meta %}

{% block content %}
  <div class="bg-dark text-white text-center py-3">
    <h1>Tugas 4 PBP - To-Do List</h1>
  </div>
  
  <div class="container text-center py-3">
    <h4>Semangat mengerjakan task-mu, {{ user }}!</h4>

    <br>
    <div class="row justify-content-center">
      <div class="col-6 col-sm-4 col-md-3">
        <a class="btn btn-dark" href="{% url 'todolist:logout' %}">Logout</a>
      </div>
      <div class="col-6 col-sm-4 col-md-3">
        <a class="btn btn-dark" href="{% url 'todolist:create_task' %}">Tambah Task</a>
      </div>
      <div class="col-6 col-sm-4 col-md-3">
        <a class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#modal">Add Task</a>
      </div>
    </div>
    <hr>

    <div class="modal fade" id="modal" data-bs-backdrop="static">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Tambah Task Baru</h5>
            <a class="btn-close" data-bs-dismiss="modal"></a>
          </div>
          <div class="modal-body">
            <form method="POST" action="">
              {% csrf_token %}
              <table class="table table-hover table-borderless align-middle">
                <tr>
                  <th>Judul: </th>
                  <td><input type="text" id="title" placeholder="Judul" class="form-control" required></td>
                </tr>
                <tr>
                  <th>Deskripsi: </th>
                  <td><input type="text" id="description" placeholder="Deskripsi" class="form-control" required></td>
                </tr>
              </table>
              <input class="btn btn-dark" type="submit" value="Tambah Task">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="row justify-content-center px-3" id="card-grid"></div>  
  </div>
{% endblock content %}